Add new server endpoint: /namespaces/:fqn
unisonweb/unison pull request #2368
Opened 2021-08-31 16:11 UTC by hojberg

## Overview
Add a new server endpoint for fetching the details of a namespace:
`/namespaces/:namespaceFQN`, can be used like so `/namespaces/base.List`.

This is served by the `NamespaceDetails` API which looks for a readme
(any capitalization) in the namespace and renders it.

## Implementation notes
The readme is looked up shallowly in the namespace branch and if found, is rendered.

Additionally I cleaned up a few things with regards to naming of the
previous `ListNamespace` module to match what it was returning. Down the
line the 2 APIs might be merged into a single `Namespaces` API.

## Interesting/controversial decisions
`Backend.renderDoc` returns a `List` and i'm not sure why. @pchiusano do you know the details of that?

## Test coverage
Tested the API and its giving the right results. We still need a better story for testing server endpoints.

## Loose ends
This is kinda slow? I'm not sure how best to debug that.

I think there's a separate effort related to working through these endpoints to make them more RESTful now that rootBranch is almost always used. I could imagine a set of endpoints like so (rough):

* `/:rootBranch/definitions/find/:query`
* `/:rootBranch/definitions/:definitionFQN`
* `/:rootBranch/namespaces/list`
* `/:rootBranch/namespaces/:namespaceFQN`

2021-08-31 22:07 UTC, pchiusano requested changes
Cool!

On the implementation, I would not go through `[ShallowListEntry]` if all you're doing is locating a term called `README`. That's going to do a bunch of extra work and might be contributing to slowness (the other thing that could be slow is doc rendering - which you can test by making the README in question a very small document).

I think that helper `renderDoc` returns a list because it's possible for a single definition to have multiple docs, like you could have two terms called `List.map.doc`.

I'll try to suggest some changes on the diff to improve the implementation of finding the README term.

2021-08-31 23:07 UTC, pchiusano commented
@hojberg check https://github.com/unisonweb/unison/pull/2368/commits/fbb62e3b6a060afe581538e34dd54b26fcdaa54c which I just pushed to this branch. This was my attempt at simplifying and to avoid needing to construct all these term results, and also avoiding a linear scan. 

I wasn't sure how to test, so can you give it another go? One possibly controversial decision is that I just look for one of `README`, `Readme`, `ReadMe`, or `readme`. Any other capitalization doesn't seem like a thing anyone would ever intentionally type... :)

2021-08-31 23:08 UTC, pchiusano approved these changes

2021-09-01 00:47 UTC, hojberg commented
@pchiusano Nice! thanks, that works great :D

2021-09-01 00:47 UTC, merged