Fix duplicate find_type(_mentions)_index entries
unisonweb/unison pull request #2538
Opened 2021-10-22 16:32 UTC by mitchellwrosen

## Overview

This PR fixes #2332.

We had duplicate rows in the `find_type_index` and `find_type_mentions_index` due to code that looked like:

```
for each member of a component,
  do some per-member stuff
  copy over the whole component's index rows
```

which was de-dented to become

```
for each member of a component,
  do some per-member stuff
copy over the whole component's index rows
```

Additionally, to guard against syncing from old databases that have this property, we now `nubOrd` the list index rows before copying over. As mentioned in a comment in the source, this could also be accomplished by putting a unique index on the index tables for the whole 6-tuple, if we want to do that some day.

## Test coverage

No automated tests were added. I did manually confirm this PR passes the Stew Test from #2332:

```
sqlite> select count(*) from find_type_index;
19206
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_index);
19206
sqlite> select count(*) from find_type_mentions_index;
112326
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_mentions_index);
112326
```

Note we have two pairs of equal numbers. Previously, the `count(*)` was far greater than the distinct `count(*)` on this database I'm testing against.

2021-10-22 18:31 UTC, pchiusano approved these changes
Wow, good catch.

It might be nice to have a "rebuild index" command at some point. 

Would one way to repair an existing codebase is just to push its root to an empty codebase? And then the `nubOrd` will take care of deduping, and then going forward `ucm` won't produce duplicates.

2021-10-22 19:24 UTC, aryairani approved these changes
Awesome! Go ahead and merge when ready.

2021-10-22 19:24 UTC, aryairani commented on codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
> +                  >>= runDest . traverse_ (flip Q.addToDependentsIndex ref')
We should split this and the other spot into its own `syncDependenciesIndex` function too, to match. Can be here or a separate PR after.

2021-10-22 19:33 UTC, aryairani commented
@mitchellwrosen So is it correct that a codebase with existing bloat can be fixed by pushing the whole thing somewhere and the pulling to a new codebase?  /cc @stew 

This workaround is also a temporary one, because all codebases will have their indexes fixed during the codebase schema migration.

2021-10-23 15:27 UTC, mitchellwrosen commented
@pchiusano / @aryairani Yeah, that'd work (at least in my head)

2021-10-24 06:33 UTC, aryairani commented
Funny, I totally missed that Paul had already asked the same question.

2021-10-24 13:31 UTC, mitchellwrosen commented on codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
> +                  >>= runDest . traverse_ (flip Q.addToDependentsIndex ref')
I added this in https://github.com/unisonweb/unison/pull/2538/commits/0f7b20d921a28b0b829ecc436819bf04fc30c9ed, and pulled in `unison-prelude` as a dependency of `codebase-sqlite`, which I think is ok, because it should be at the root of everything and not contain anything parser-typechecker specific.

2021-10-24 17:13 UTC, aryairani requested changes

2021-10-24 17:13 UTC, aryairani commented on codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
> +
I'm surprised no existing push-pull tests failed on this `undefined`, what am I missing?

2021-10-24 17:15 UTC, aryairani commented on codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
> +
Disregard; they did fail on this `undefined`.

2021-10-24 17:41 UTC, aryairani approved these changes

2021-10-25 21:57 UTC, ChrisPenner approved these changes
Thanks for doing this; I think this provides us with at least two object lessons:

1. Aggressively pull out helpers so that the control-flow and nesting at the top level becomes clear (e.g. operate at a single layer of abstraction at a time)
2. Add as many unique indexes as we can, even if we _think_ we don't need them

2021-10-25 22:02 UTC, merged

2021-10-26 00:28 UTC, aryairani commented
> 2. Add as many unique indexes as we can, even if we _think_ we don't need them

I'd push back on this somewhat — I suspect I left this out on purpose to reduce the size of the index on disk (and I'd want to do a space comparison before adding it back in), though in that case I ought to have left a comment with some concrete numbers.

Or, I should have added the unique constraint during development & testing, and then dropped it before releasing it to the public, which would have caught this bug too.