Move reflog into sqlite
unisonweb/unison pull request #3364
Opened 2022-08-25 18:55 UTC by ChrisPenner

## Overview

<img width="903" alt="image" src="https://user-images.githubusercontent.com/6439644/186746023-6525375c-917b-4464-8066-6be6e96ebde5.png">

## Implementation notes

How does it accomplish it, in broad strokes? i.e. How does it change the Haskell codebase?

## Interesting/controversial decisions

Include anything that you thought twice about, debated, chose arbitrarily, etc. 
What could have been done differently, but wasn't? And why?

## Test coverage

Have you included tests (which could be a transcript) for this change, or is it somehow covered by existing tests? 

Would you recommend improving the test coverage (either as part of this PR or as a separate issue) or do you think it’s adequate?

## Loose ends

Link to related issues that address things you didn't get to. Stuff you encountered on the way and decided not to include in this PR.

2022-08-26 17:11 UTC, ChrisPenner commented on parser-typechecker/src/Unison/Codebase/Reflog.hs
> -{-# LANGUAGE ViewPatterns #-}
Everywhere just uses the `Reflog.Entry` type from `U.Codebase.Reflog` now.

2022-08-26 22:20 UTC, aryairani requested changes
Awesome. A couple thoughts:

> Note that the new reflog table only has (timestamp, new root causal hash, reason); we no longer track a from causal, since it will always just be the causal before it, and we don't show this in the output anyways.

I think we still want to keep the old causal hash, just in case it somehow isn't the same as the entry before it. (The first entry has no entry before it, for example.)  Git is the same, in that it records both, but only shows the new hash in the output. We could also consider including both in the output (`#abc -> #def`), but it's messier from a "numbered output" perspective.

> We don't have timestamp info for old entries

Whoops!

> so we just import them all at the "current time", but add second offsets such that they appear in the correct chronological order.

Can there be a situation where I have 100 old entries and end up dating them into the future, and then a new user-generated entry is stuck in the middle of them (another case where I'd want my two causal hash ids per row again explicitly)? If it must be seconds and not nanoseconds or something (and even if it could be nanoseconds), putting them in the past would be safer.

> I don't delete the old reflog file, I could, but there doesn't seem to be a good reason to and deleting files on the user's system is always a little bit sketch.

:+1: If there's an easy spot to, you could tell the user we moved it and they can delete the file if they want.

2022-08-29 15:01 UTC, ChrisPenner commented
> I think we still want to keep the old causal hash, just in case it somehow isn't the same as the entry before it

How could this happen and what does it mean?
If it just means we have a bug and forgot to add something to the reflog I'd rather we fix that error rather than try to cover it up 😓 

If we want confidence in that behaviour we could try adding a "reason" to the actual "updateRoot" command rather than having a separate "appendReflog" command.

> Can there be a situation where I have 100 old entries and end up dating them into the future

No, the second offsets go into the past.

2022-08-29 15:50 UTC, ChrisPenner commented
@aryairani  

* I changed `putRootBranch` so it now accepts a reason and appends to the reflog in the same transaction which updates the root branch, so that should improve our confidence that the reflog is correct.
* I added the `from` causal to the reflog entries
* I added a note to the migration that the user can delete the old reflog file

~I just have to re-test things now 👍🏼~ ✅

2022-08-30 22:35 UTC, aryairani commented
> I don't have any issue with adding the `from`, but how could this happen and what does it mean? (besides the first entry of course). If it just means we have a bug and forgot to add something to the reflog I'd rather we fix that error rather than try to cover it up 😓

Yeah.  It shouldn't happen (except in that case), and we should fix whatever errors we find. This won't be covering them up, but it will help us not lose data in those cases. It's not the strongest rationale, for sure.  I wonder what the reasons for git also including the old and new hashes in their reflog were too, could be interesting.

2022-08-31 00:39 UTC, aryairani commented on parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema5To6.hs
> +      let offsetTime = addUTCTime (negate $ fromInteger @NominalDiffTime n) now
as a sanity check now, wdyt about adding a screenshot of a migrated reflog demoing this?

2022-08-31 00:41 UTC, aryairani commented on unison-src/transcripts/reflog.output.md
> +  3.   now    builtins.merge   #43lqh9lfp3
How hard would it be to show the initial namespace again? 😅

2022-08-31 00:42 UTC, aryairani commented on parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema5To6.hs
> +      let offsetTime = addUTCTime (negate $ fromInteger @NominalDiffTime n) now
I guess the transcript does enough here, so you can disregard.

2022-08-31 00:48 UTC, aryairani commented on parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema5To6.hs
> +      let offsetTime = addUTCTime (negate $ fromInteger @NominalDiffTime n) now
(Actually disregard the disregard; the transcript is unrelated to reflog migration)

2022-08-31 13:05 UTC, aryairani commented
Note: I could imagine having some reason to do multiple `putRootBranch` in a single command that should possibly just get a single reflog update, but this seems good for now.

2022-08-31 13:12 UTC, aryairani requested changes
I left one request for display fix and one request for a sanity screenshot but otherwise looks good!

2022-09-01 21:47 UTC, ChrisPenner commented
Here's the beginning and end of history:


<img width="918" alt="image" src="https://user-images.githubusercontent.com/6439644/188018769-64a17f26-bc49-4614-a746-8b90ad3127f1.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/6439644/188018797-24b32982-dda2-4a60-bbe5-401d2ff7e5f4.png">

2022-09-02 15:41 UTC, aryairani commented
Sweet!

2022-09-02 15:41 UTC, aryairani approved these changes

2022-09-02 19:49 UTC, aryairani approved these changes

2022-09-02 19:50 UTC, aryairani commented on parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema5To6.hs
> +  Sqlite.unsafeIO . putStrLn $ "I migrated old reflog entries from " <> reflogPath <> " into the codebase, you may delete that file now if you like."
```suggestion
  Sqlite.unsafeIO . putStrLn $ "I migrated old reflog entries from " <> reflogPath <> " into the codebase; you may delete that file now if you like."
```

2022-09-02 19:52 UTC, merged