Change error message, constructor, functions from `vector` to `list` (closes  #3360)
unisonweb/unison pull request #3380
Opened 2022-09-01 16:54 UTC by cstml

## Overview

Changes the error pretty print error message from `vector` to `list` #3360 and rephrases it in a more naturally reading way. 

## Implementation notes

The PR also reflects the change at the type level - changing the name of the Constructor and the functions.

## Interesting/controversial decisions

None

## Test coverage

Tests have been refactored to include the function binder change.

## Loose ends

None

2022-09-02 15:44 UTC, aryairani commented
Hi @cstml, thanks for this patch — could you add yourself to the `CONTRIBUTORS.markdown` to acknowledge acceptance of Unison's MIT license?

2022-09-02 19:47 UTC, aryairani requested changes
Looks good! Just need to add yourself to `CONTRIBUTORS.markdown`.

2022-09-12 07:32 UTC, cstml commented
Done.

2022-09-14 14:00 UTC, aryairani approved these changes

2022-09-14 14:00 UTC, merged