Fix build with cabal
unisonweb/unison pull request #3722
Opened 2023-01-01 21:19 UTC by jneira

The pr updates cabal.project to adjust it to last structural changes.
Unfortunately the codebase now uses th referencing files with relative paths and stack and cabal sets a different cwd 😟 
Not sure how coud we solve that behaviour tbh. I believe atleats stack sets some C defs and we could add CPP conditions but i don't like it at all.

Another caveat: the haskelinecommit 2944b11d19ee034c48276edc991736105c9d6143 does not exist anymore.
It is being referenced in stack.yaml bue i am not sure how is working. I've replicated the commit in my repo, but obviusly it cant be the definitive solution.

The cabal build should be checked in ci to keep it sync (even with an optinal job)

2023-01-03 14:51 UTC, jneira commented
> Unfortunately the codebase now uses th referencing files with relative paths and stack and cabal sets a different cwd 😟 (https://github.com/haskell/haskell-language-server/issues/481)

I expected ci should fail due to changes in Query.hs 🤔

2023-01-06 17:42 UTC, aryairani requested changes
Hi @jneira — we don't currently support building with cabal beyond what's in contrib/.

However, we might support cabal in the future, so I'm averse to adding cabal.project to .gitignore.

> Not sure how coud we solve that behaviour tbh.

We use symlinks (`sql/`) because stack and haskell-language-server already use different cwds. We use more symlinks (`unison/`) because we have another project that uses `unison` as a submodule under the `unison/` path.

Maybe adding more symlinks will work for you, but for the submodule reason above, we don't want to change `Query.hs`

If you want to merge just the `contrib/cabal.project` changes, possibly another symlink, and some `development.markdown` changes, that would be okay.

2023-01-07 14:21 UTC, jneira commented
Thanks for the feedback: sure, will revert the .gitignore, great to know cabal could be a first citizen. 😄  
hls support for cabal is better than for stack and that is a good argument to support cabal imo (the reason hls uses the same cwd as cabal is #481)

> Maybe adding more symlinks will work for you, but for the submodule reason above, we don't want to change Query.hs

Sure, my fault, i did not check lastest instructions for building in windows and i did not activate symlinking. `Query.hs`works with any change after activate them.

I am about to upload last versions with the needed changes

2023-01-07 15:40 UTC, jneira commented
@aryairani changes done, still left the issue with the haskeline commit used in stack.yaml

The commit does not belong to any branch: https://github.com/judah/haskeline/commit/d6c2643b0d5c19be7e440615c6f84d603d4bc648

And cabal throw an error when trying to fetch it:

```
fatal: Could not parse object 'd6c2643b0d5c19be7e440615c6f84d603d4bc648'.
```

(it works for non orphan commits)

Should be cherry-pick the commit to the unison haskeline fork? I think it would be good to not depend on an orphaned commit of a external repo

2023-05-27 04:51 UTC, aryairani commented
Hi @jneira sorry I missed your last messages. The haskeline issue should be resolved now if you want to try again 😬

2023-05-31 20:34 UTC, dolio commented
This looks good to me. It closely matches what I use locally.

Although, I don't even bother with a custom haskelline/configurator commit. I just use something from hackage and haven't noticed problems.

2023-05-31 20:35 UTC, aryairani approved these changes

2023-05-31 20:35 UTC, merged