Move to Racket
unisonweb/unison pull request #3931
Opened 2023-04-25 12:25 UTC by SystemFw

## Overview

Simplifies the scheme backend code to only support Racket, given that the Chez backend is starting to seriously bitrot.

## Implementation notes

I've simplified the directory structure and a bunch of the files.

## Interesting/controversial decisions

I've pushed a `last-working-chez` tag on trunk on the latest commit that fully supports both backends

## Test coverage

Tested via the unison tests and the racket tests

## Loose ends

We could/should also port all the r6rs code to Racket, I'm debating whether to do that in this PR or as we go along.

2023-04-25 16:16 UTC, pchiusano approved these changes

2023-04-26 17:20 UTC, dolio requested changes, later dismissed

2023-04-26 17:20 UTC, dolio commented on unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
> +            Path.fromList $ NameSegment <$> ["public", "internal", "racket"]
This shouldn't be merged in, right?

2023-04-26 17:25 UTC, pchiusano commented on unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
> +            Path.fromList $ NameSegment <$> ["public", "internal", "racket"]
We just discussed this. It'll be changed back to "trunk" after the Unison repo is updated, just before merging this PR.

2023-04-26 17:54 UTC, merged