Fix many pattern not backtracking
unisonweb/unison pull request #4790
Opened 2024-03-13 19:43 UTC by dolio

Turns out, `Pattern.many` had the same non-backtracking problem as the functions in #3540. This applies the same fix.

This change actually breaks the http library (which was accidentally relying on the erroneous behavior), so it shouldn't be merged yet. I'll let @ceedubs decide when it should be.

2024-03-13 20:01 UTC, aryairani commented
Thanks @dolio
@ceedubs Lmk how we should proceed

2024-03-14 06:16 UTC, aryairani approved these changes

2024-03-14 16:53 UTC, ceedubs commented
Should there be a test or two for this?

2024-03-17 14:29 UTC, aryairani requested changes
@dolio Could you add a regression test somewhere, and then we'll get it merged.

2024-03-18 19:46 UTC, ceedubs approved these changes
Thanks!

2024-03-19 03:12 UTC, aryairani approved these changes

2024-03-19 03:12 UTC, merged