feat: report merge precondition violations in `todo`
unisonweb/unison pull request #5177
Opened 2024-07-03 16:01 UTC by mitchellwrosen

## Overview

Fixes #5088

This PR amends `todo` to report merge precondition violations (constructor aliases, missing constructor names, nested decl aliases, and stray constructors).

## Test coverage

I've added transcripts that demonstrate this feature

2024-07-05 19:36 UTC, aryairani requested changes
Nice!
I left a couple questions/comments

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.md
> -project/main> todo
fwiw I think `project` is fine in a transcript too, possibly clearer than `scratch`; I know we are de facto standardizing on `scratch`.

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +  These terms call `todo`.
I think the `:` was more correct here?

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +  These terms do not have any names in the current namespace.
Same (`:` vs `.`)

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +  bar#cq22mm4sca
* Is this just a PPE issue that causes it to show `foo` instead of a kind of `bar`?
* Would it be hard to get it to show them both as `bar`-something?
* This should be an indented, newline separated list, right?

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +  representing library dependencies. Please move or remove it.
It would be nice if this said the name of the bad thing, but hopefully terms in `lib` are going away altogether before we care too much. So nevermind.

We should add a ticket to modify `move`/`alias` to not allow destinations in `lib` and hope that it doesn't mess up any hacky-but-necessary workflows.

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +
Could use a hint here, to `view` and then... can they use `alias` to create these names by hash if they don't already exist? Or what's the fix in this case?

2024-07-05 19:36 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +
Would it be hard to show what type they belong to?

2024-07-05 19:40 UTC, aryairani commented on unison-src/transcripts/todo.output.md
> +  representing library dependencies. Please move or remove it.
https://github.com/unisonweb/unison/issues/5184

2024-07-09 22:11 UTC, mitchellwrosen commented on unison-src/transcripts/todo.output.md
> +
I thought it wouldn't be that bad to pipe things through, but it's looking like more piping than I anticipated. I'm going to make a ticket to track.

2024-07-09 23:00 UTC, mitchellwrosen commented
@aryairani I think I addressed everything except this one https://github.com/unisonweb/unison/issues/5197, for which I made that ticket

2024-07-10 17:26 UTC, aryairani approved these changes

2024-07-10 17:28 UTC, merged